### ISSUE TITLE
在Windows端会出现asyncio_setup() got an unexpected keyword argument 'reload'的异常

### ISSUE THREAD

**Issue by AdamXuD** [kexue-z/nonebot-plugin-htmlrender#11]
操作系统： Windows 10 19042.1466
Python 版本： Python 3.9.5
uvicorn 版本：uvicorn 0.17.6

03-13 22:33:01 [WARNING] nonebot_plugin_htmlrender | 检测到当前为 Windows 系统，已自动注入猴子补丁
03-13 22:33:05 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
03-13 22:33:05 [SUCCESS] nonebot | Running NoneBot...
03-13 22:33:05 [DEBUG] nonebot | Loaded adapters: OneBot V11
python-BaseException
Traceback (most recent call last):
  File "D:\Python\Python39\lib\site-packages\uvicorn\loops\auto.py", line 3, in auto_loop_setup
    import uvloop  # noqa
ModuleNotFoundError: No module named 'uvloop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\JetBrain\apps\PyCharm-P\ch-0\211.7442.45\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\JetBrain\apps\PyCharm-P\ch-0\211.7442.45\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/Works/meguchan-lte/bot.py", line 36, in <module>
    nonebot.run(app="__mp_main__:app")
  File "D:\Python\Python39\lib\site-packages\nonebot\__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "D:\Python\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 168, in run
    uvicorn.run(
  File "D:\Python\Python39\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "D:\Python\Python39\lib\site-packages\uvicorn\server.py", line 59, in run
    self.config.setup_event_loop()
  File "D:\Python\Python39\lib\site-packages\uvicorn\config.py", line 506, in setup_event_loop
    loop_setup(reload=self.reload)
  File "D:\Python\Python39\lib\site-packages\uvicorn\loops\auto.py", line 7, in auto_loop_setup
    loop_setup(reload=reload)
TypeError: asyncio_setup() got an unexpected keyword argument 'reload'

推测原因是在最新的uvicorn中，在uvicorn/loops/auto.py中asyncio_setup的调用方式发生改变：
由loop_setup() 变为 loop_setup(reload=reload)

同时asyncio_setup的函数签名也已由
def asyncio_setup() -> None:
    ...
变为
def asyncio_setup(reload: bool = False) -> None:
    ...

但是在本项目的patch.py中却试图用一个无形参的asyncio_setup()去替换有形参的asyncio_setup(reload: bool = False) 故发生了上述异常

https://github.com/encode/uvicorn/commit/81802ceee2a2c62f0b10f78e2b6366b47bc76f72#diff-c93420ffcc3d45d9385926cfe72deaaccec6dbce77c7aa2458f92db7e09b9cecL7-R7

**Comment by AdamXuD** [comment]
当我将uvicorn版本降回0.15.0 则不会报上述异常
