### ISSUE TITLE
启动过程中Playwright，asyncio，starlette等报错

### ISSUE THREAD

**Issue by WindraiteLesd** [kexue-z/nonebot-plugin-htmlrender#15]
系统版本Windows Server 2019
Python版本3.9.7
nonebot版本为2.0.0-beta.2
未安装其他任何插件

```
04-30 16:20:27 [SUCCESS] nonebot | NoneBot is initializing...
04-30 16:20:27 [INFO] nonebot | Current Env: dev
04-30 16:20:27 [DEBUG] nonebot | Loaded Config
04-30 16:20:28 [DEBUG] nonebot | Succeeded to load adapter "mirai V2"
04-30 16:20:28 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_htmlrender"
04-30 16:20:28 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
04-30 16:20:28 [SUCCESS] nonebot | Running NoneBot...
04-30 16:20:28 [DEBUG] nonebot | Loaded adapters: mirai V2
04-30 16:20:28 [INFO] uvicorn | Will watch for changes in these directories: ['C:\\Users\\Administrator\\Desktop\\bot\\plugins\\nonebot2\\LesdNoneBot2']
04-30 16:20:28 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
04-30 16:20:28 [INFO] uvicorn | Started reloader process [10056] using watchgod
04-30 16:20:29 [SUCCESS] nonebot | NoneBot is initializing...
04-30 16:20:29 [INFO] nonebot | Current Env: dev
04-30 16:20:27 [DEBUG] nonebot | Loaded Config
04-30 16:20:29 [DEBUG] nonebot | Succeeded to load adapter "mirai V2"
04-30 16:20:30 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_htmlrender"
04-30 16:20:30 [WARNING] uvicorn | The --reload flag should not be used in production on Windows.
04-30 16:20:30 [INFO] uvicorn | Started server process [9124]
04-30 16:20:30 [INFO] uvicorn | Waiting for application startup.

Task exception was never retrieved
future: <Task finished name='Task-4' coro=<Connection.run() done, defined at C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\playwright\_impl\_connection.py:174> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\playwright\_impl\_connection.py", line 181, in run
    await self._transport.connect()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\playwright\_impl\_transport.py", line 132, in connect
    raise exc
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
04-30 16:20:30 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\starlette\routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\starlette\routing.py", line 518, in __aenter__
    await self._router.startup()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\starlette\routing.py", line 598, in startup
    await handler()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 27, in init
    browser = await get_browser(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 40, in get_browser
    return _browser or await init(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 26, in init
    _playwright = await async_playwright().start()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\playwright\_impl\_connection.py", line 181, in run
    await self._transport.connect()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\playwright\_impl\_transport.py", line 132, in connect
    raise exc
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

04-30 16:20:30 [ERROR] uvicorn | Application startup failed. Exiting.
```

使用了最低要求的Playwright 1.17.2版本依旧出现该错误

**Comment by kexue-z** [comment]
https://playwright.dev/python/docs/intro#incompatible-with-selectoreventloop-of-asyncio-on-windows

windows 上好像不太行

**Comment by WindraiteLesd** [comment]
有没有替代方案

**Comment by WindraiteLesd** [comment]
由FAST API导致的问题，需要切换Driver
https://v2.nonebot.dev/docs/tutorial/choose-driver#fastapi%E9%BB%98%E8%AE%A4
