### ISSUE TITLE
使用0.0.4.7时报错

### ISSUE THREAD

**Issue by benx1n** [kexue-z/nonebot-plugin-htmlrender#21]
windows下使用0.0.4.7时，无论是否开启uvicorn的reload均报错
回退至0.0.4.6后并关闭reload则正常
```
05-26 23:07:53 [WARNING] nonebot_plugin_htmlrender | 检测到当前为 Windows 系统，已自动注入猴子补丁
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\uvicorn\loops\auto.py", line 3, in auto_loop_setup
    import uvloop  # noqa
ModuleNotFoundError: No module named 'uvloop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\nonebot\__init__.py", line 259, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\uvicorn\server.py", line 59, in run
    self.config.setup_event_loop()
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\uvicorn\config.py", line 506, in setup_event_loop
    loop_setup(reload=self.reload)
  File "C:\Users\Administrator\miniconda3\envs\nonebot2\lib\site-packages\uvicorn\loops\auto.py", line 7, in auto_loop_setup
    loop_setup(reload=reload)
TypeError: asyncio_setup() got an unexpected keyword argument 'reload'
```

**Comment by kexue-z** [comment]
草 我还不知道这东西失效了 寄！
回滚吧
