### ISSUE TITLE
装Firefox和依赖的时候报错退出

### ISSUE THREAD

**Issue by xharaut** [kexue-z/nonebot-plugin-htmlrender#28]
系统：Ubuntu20.04
```
[INFO] nonebot-plugin-htmlrender-master | 正在安装 firefox
[INFO] nonebot-plugin-htmlrender-master | 正在安装依赖
Installing dependencies...
命中:1 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal InRelease
命中:2 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates InRelease
命中:3 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-backports InRelease
命中:4 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security InRelease
正在读取软件包列表... 完成
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
注意，选中 'libfontconfig1' 而非 'libfontconfig'
fonts-liberation 已经是最新版 (1:1.07.4-11)。
libatk1.0-0 已经是最新版 (2.35.1-1ubuntu2)。
libatspi2.0-0 已经是最新版 (2.36.0-2)。
libcairo-gobject2 已经是最新版 (1.16.0-4ubuntu1)。
libcairo2 已经是最新版 (1.16.0-4ubuntu1)。
libdbus-glib-1-2 已经是最新版 (0.110-5fakssync1)。
libepoxy0 已经是最新版 (1.5.4-1)。
libfontconfig1 已经是最新版 (2.13.1-2ubuntu3)。
libgstreamer1.0-0 已经是最新版 (1.16.2-2)。
libhyphen0 已经是最新版 (2.8.8-7)。
libnotify4 已经是最新版 (0.7.9-1ubuntu2)。
libnspr4 已经是最新版 (2:4.25-1)。
libopus0 已经是最新版 (1.3.1-0ubuntu1)。
libpango-1.0-0 已经是最新版 (1.44.7-2ubuntu4)。
libpangocairo-1.0-0 已经是最新版 (1.44.7-2ubuntu4)。
libpangoft2-1.0-0 已经是最新版 (1.44.7-2ubuntu4)。
libpng16-16 已经是最新版 (1.6.37-2)。
libsoup2.4-1 已经是最新版 (2.70.0-1)。
libvpx6 已经是最新版 (1.8.2-1build1)。
libwayland-client0 已经是最新版 (1.18.0-1)。
libwayland-egl1 已经是最新版 (1.18.0-1)。
libwayland-server0 已经是最新版 (1.18.0-1)。
libwoff1 已经是最新版 (1.0.2-1build2)。
libxcb-shm0 已经是最新版 (1.14-2)。
libxcb1 已经是最新版 (1.14-2)。
libxcomposite1 已经是最新版 (1:0.4.5-1)。
libxcursor1 已经是最新版 (1:1.2.0-2)。
libxdamage1 已经是最新版 (1:1.1.5-2)。
libxext6 已经是最新版 (2:1.3.4-0ubuntu1)。
libxfixes3 已经是最新版 (1:5.0.3-2)。
libxi6 已经是最新版 (2:1.7.10-0ubuntu1)。
libxkbcommon0 已经是最新版 (0.10.0-1)。
libxrandr2 已经是最新版 (2:1.5.2-0ubuntu1)。
libxrender1 已经是最新版 (1:0.9.10-1)。
libxshmfence1 已经是最新版 (1.3-1)。
libxslt1.1 已经是最新版 (1.1.34-4)。
libxt6 已经是最新版 (1:1.1.5-1)。
libxtst6 已经是最新版 (2:1.2.3-1)。
ttf-unifont 已经是最新版 (1:12.0.01-2)。
xfonts-scalable 已经是最新版 (1:1.0.3-1.1)。
fonts-ipafont-gothic 已经是最新版 (00303-18ubuntu1)。
fonts-tlwg-loma-otf 已经是最新版 (1:0.7.1-3)。
fonts-wqy-zenhei 已经是最新版 (0.9.45-7ubuntu1)。
gstreamer1.0-libav 已经是最新版 (1.16.2-2)。
gstreamer1.0-plugins-bad 已经是最新版 (1.16.2-2.1ubuntu1)。
libenchant1c2a 已经是最新版 (1.6.0-11.3build1)。
ttf-ubuntu-font-family 已经是最新版 (1:0.83-4ubuntu1)。
xfonts-cyrillic 已经是最新版 (1:1.0.4)。
fonts-noto-color-emoji 已经是最新版 (0~20200916-1~ubuntu20.04.1)。
gstreamer1.0-plugins-base 已经是最新版 (1.16.2-4ubuntu0.1)。
gstreamer1.0-plugins-good 已经是最新版 (1.16.2-1ubuntu2.1)。
libasound2 已经是最新版 (1.2.2-2.1ubuntu2.5)。
libatk-bridge2.0-0 已经是最新版 (2.34.2-0ubuntu2~20.04.1)。
libcups2 已经是最新版 (2.3.1-9ubuntu1.2)。
libdbus-1-3 已经是最新版 (1.12.16-2ubuntu2.2)。
libdrm2 已经是最新版 (2.4.107-8ubuntu1~20.04.2)。
libegl1 已经是最新版 (1.3.2-1~ubuntu0.20.04.2)。
libevdev2 已经是最新版 (1.9.0+dfsg-1ubuntu0.2)。
libfreetype6 已经是最新版 (2.10.1-2ubuntu0.2)。
libgbm1 已经是最新版 (21.2.6-0ubuntu0.1~20.04.2)。
libgdk-pixbuf2.0-0 已经是最新版 (2.40.0+dfsg-3ubuntu0.2)。
libgl1 已经是最新版 (1.3.2-1~ubuntu0.20.04.2)。
libgles2 已经是最新版 (1.3.2-1~ubuntu0.20.04.2)。
libglib2.0-0 已经是最新版 (2.64.6-1~ubuntu20.04.4)。
libgstreamer-gl1.0-0 已经是最新版 (1.16.2-4ubuntu0.1)。
libgtk-3-0 已经是最新版 (3.24.20-0ubuntu1.1)。
libharfbuzz-icu0 已经是最新版 (2.6.4-1ubuntu4.2)。
libharfbuzz0b 已经是最新版 (2.6.4-1ubuntu4.2)。
libicu66 已经是最新版 (66.1-2ubuntu2.1)。
libjpeg-turbo8 已经是最新版 (2.0.3-0ubuntu1.20.04.1)。
libnss3 已经是最新版 (2:3.49.1-1ubuntu1.8)。
libopengl0 已经是最新版 (1.3.2-1~ubuntu0.20.04.2)。
libopenjp2-7 已经是最新版 (2.3.1-1ubuntu4.20.04.1)。
libsecret-1-0 已经是最新版 (0.20.4-0ubuntu1)。
libwebp6 已经是最新版 (0.6.1-2ubuntu0.20.04.1)。
libwebpdemux2 已经是最新版 (0.6.1-2ubuntu0.20.04.1)。
libx11-6 已经是最新版 (2:1.6.9-2ubuntu1.2)。
libx11-xcb1 已经是最新版 (2:1.6.9-2ubuntu1.2)。
libxml2 已经是最新版 (2.9.10+dfsg-5ubuntu0.20.04.3)。
ffmpeg 已经是最新版 (7:4.2.7-0ubuntu0.1)。
xvfb 已经是最新版 (2:1.20.13-1ubuntu1~20.04.3)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
07-23 16:42:22 [ERROR] uvicorn | Traceback (most recent call last):
  File "/home/xharaut/zhenxun_bot-0.1.6.1/nonebot-plugin-htmlrender-master/nonebot_plugin_htmlrender/browser.py", line 29, in init
    _browser = await launch_browser(**kwargs)
  File "/home/xharaut/zhenxun_bot-0.1.6.1/nonebot-plugin-htmlrender-master/nonebot_plugin_htmlrender/browser.py", line 41, in launch_browser
    return await _playwright.firefox.launch(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 11793, in launch
    await self._async(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> /root/.cache/ms-playwright/firefox-1323/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-t4gGYA -juggler-pipe -silent
<launched> pid=11088
[pid=11088][err] Running Nightly as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by xharaut.)
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/firefox-1323/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-t4gGYA -juggler-pipe -silent
<launched> pid=11088
[pid=11088][err] Running Nightly as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by xharaut.)
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/home/xharaut/zhenxun_bot-0.1.6.1/nonebot-plugin-htmlrender-master/nonebot_plugin_htmlrender/__init__.py", line 25, in init
    browser = await get_browser(**kwargs)
  File "/home/xharaut/zhenxun_bot-0.1.6.1/nonebot-plugin-htmlrender-master/nonebot_plugin_htmlrender/browser.py", line 45, in get_browser
    return _browser or await init(**kwargs)
  File "/home/xharaut/zhenxun_bot-0.1.6.1/nonebot-plugin-htmlrender-master/nonebot_plugin_htmlrender/browser.py", line 32, in init
    _browser = await launch_browser(**kwargs)
  File "/home/xharaut/zhenxun_bot-0.1.6.1/nonebot-plugin-htmlrender-master/nonebot_plugin_htmlrender/browser.py", line 41, in launch_browser
    return await _playwright.firefox.launch(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 11793, in launch
    await self._async(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-NhgnSrs7-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> /root/.cache/ms-playwright/firefox-1323/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-lpYADz -juggler-pipe -silent
<launched> pid=11634
[pid=11634][err] Running Nightly as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by xharaut.)
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/firefox-1323/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-lpYADz -juggler-pipe -silent
<launched> pid=11634
[pid=11634][err] Running Nightly as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by xharaut.)
============================================================

[ERROR] uvicorn | Application startup failed. Exiting.
```

**Comment by kexue-z** [comment]
你截的报错像艺术品一样.jpg

**Comment by kexue-z** [comment]
`Running Nightly as root in a regular user's session is not supported.`

意思是你用了普通的用户运行了root用户下的浏览器吧

**Comment by kexue-z** [comment]
https://github.com/kexue-z/nonebot-plugin-htmlrender/issues/29
