### ISSUE TITLE
不适配centos7？

### ISSUE THREAD

**Issue by zhzRedstone** [kexue-z/nonebot-plugin-htmlrender#6]
01-02 14:04:52 [INFO] nonebot_plugin_htmlrender | 正在安装 chromium
01-02 14:04:52 [ERROR] uvicorn | Traceback (most recent call last):
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/nonebot_plugin_htmlrender/browser.py", line 28, in init
    _browser = await launch_browser(**kwargs)
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/nonebot_plugin_htmlrender/browser.py", line 36, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 11602, in launch
    await self._async(
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 88, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error:
╔════════════════════════════════════════════════════════════╗
║ Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     playwright install-deps                                ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/starlette/routing.py", line 540, in lifespan
    async for item in self.lifespan_context(app):
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/starlette/routing.py", line 481, in default_lifespan
    await self.startup()
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/starlette/routing.py", line 516, in startup
    await handler()
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/nonebot_plugin_htmlrender/__init__.py", line 20, in init
    browser = await get_browser(**kwargs)
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/nonebot_plugin_htmlrender/browser.py", line 40, in get_browser
    return _browser or await init(**kwargs)
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/nonebot_plugin_htmlrender/browser.py", line 31, in init
    _browser = await launch_browser(**kwargs)
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/nonebot_plugin_htmlrender/browser.py", line 36, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 11602, in launch
    await self._async(
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 88, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/root/.virtualenvs/hongshibot_venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error:
╔════════════════════════════════════════════════════════════╗
║ Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     playwright install-deps                                ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

01-02 14:04:52 [ERROR] uvicorn | Application startup failed. Exiting.
(hongshibot_venv) [root@VM-12-5-centos hongshibot]# playwright install-deps
Installing Ubuntu dependencies...
sh: apt-get: command not found

**Comment by kexue-z** [comment]
这是playwright没有安装成功
参考https://github.com/kumaraditya303/playwright-centos/blob/master/Dockerfile
安装需要的库
