### ISSUE TITLE
疑似启动playwright报错？

### ISSUE THREAD

**Issue by VAHua** [kexue-z/nonebot-plugin-htmlrender#79]
在issues里面转了一圈，也发现了有playwright报错，解决办法是 FASTAPI_RELOAD=false，但是我改了之后也无法解决。环境是conda，python版本3.10
[](https://github.com/kexue-z/nonebot-plugin-htmlrender/issues/25)
报错日志如下：
```
10-25 17:00:57 [SUCCESS] nonebot | Running NoneBot...
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.run() done, defined at D:\ProgramData\anaconda3\envs\bot\lib\site-packages\playwright\_i
mpl\_connection.py:269> exception=NotImplementedError()>
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\bot\lib\site-packages\playwright\_impl\_connection.py", line 276, in run
    await self._transport.connect()
  File "D:\ProgramData\anaconda3\envs\bot\lib\site-packages\playwright\_impl\_transport.py", line 133, in connect
    raise exc
  File "D:\ProgramData\anaconda3\envs\bot\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "D:\ProgramData\anaconda3\envs\bot\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "D:\ProgramData\anaconda3\envs\bot\lib\asyncio\base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "D:\ProgramData\anaconda3\envs\bot\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
10-25 17:00:57 [ERROR] uvicorn | Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\bot\lib\site-packages\starlette\routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "D:\ProgramData\anaconda3\envs\bot\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\ProgramData\anaconda3\envs\bot\lib\site-packages\nonebot\drivers\fastapi.py", line 153, in _lifespan_manager
    await self._lifespan.startup()
  File "D:\ProgramData\anaconda3\envs\bot\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 42, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "D:\ProgramData\anaconda3\envs\bot\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 36, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "D:\ProgramData\anaconda3\envs\bot\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 38, in init
    browser = await get_browser(**kwargs)
  File "D:\ProgramData\anaconda3\envs\bot\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 61, in get_browser
    return _browser if _browser and _browser.is_connected() else await init(**kwargs)
  File "D:\ProgramData\anaconda3\envs\bot\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 32, in init
    _playwright = await async_playwright().start()
  File "D:\ProgramData\anaconda3\envs\bot\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "D:\ProgramData\anaconda3\envs\bot\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "D:\ProgramData\anaconda3\envs\bot\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "D:\ProgramData\anaconda3\envs\bot\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "D:\ProgramData\anaconda3\envs\bot\lib\asyncio\base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "D:\ProgramData\anaconda3\envs\bot\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

10-25 17:00:57 [ERROR] uvicorn | Application startup failed. Exiting.
```

**Comment by danel-phang** [comment]
相同问题,同问

**Comment by xANoyU** [comment]
同样的问题 尝试使用poetry启动也报这个错误

**Comment by ElainaFanBoy** [comment]
同样的问题，请问大佬解决了没，我环境也是conda+py3.10
